#!/usr/bin/env bash
#
# publish.sh - install or uninstall this single skill for local AI coding tools.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_FILE="$ROOT/SKILL.md"
VERSION="$(git -C "$ROOT" describe --tags --always --dirty 2>/dev/null || echo nogit)"

CLAUDE_SKILLS_DIR="$HOME/.claude/skills"
CODEX_SKILLS_DIR="$HOME/.agents/skills"
OPENCODE_SKILLS_DIR="$HOME/.config/opencode/skills"

ALL_TOOLS=(claude codex opencode)
DRY=0
FORCE=0
SKILL=""
TOOLS=()

log() { printf '%s\n' "$*"; }

usage() {
  cat <<EOF
publish.sh - install or uninstall this skill for local AI coding tools

Usage:
  ./publish.sh [options] install [all|claude|codex|opencode...]
  ./publish.sh [options] uninstall [all|claude|codex|opencode...]
  ./publish.sh status

Options:
  -n, --dry-run   Preview install/uninstall without writing
  --force         Uninstall even when the installed SKILL.md is not marked as managed
  -h, --help      Show help

Examples:
  ./publish.sh -n install all
  ./publish.sh install codex
  ./publish.sh uninstall all
  ./publish.sh status
EOF
}

skill_name() {
  awk '
    BEGIN { in_fm = 0 }
    NR == 1 && $0 == "---" { in_fm = 1; next }
    in_fm && $0 == "---" { exit }
    in_fm && /^name:[[:space:]]*/ {
      sub(/^name:[[:space:]]*/, "")
      gsub(/^["'\'']|["'\'']$/, "")
      print
      exit
    }
  ' "$SKILL_FILE"
}

require_skill() {
  [ -f "$SKILL_FILE" ] || { log "Missing SKILL.md at $SKILL_FILE"; exit 1; }
  SKILL="$(skill_name)"
  [ -n "$SKILL" ] || { log "Could not read skill name from SKILL.md frontmatter"; exit 1; }
}

tool_dir() {
  case "$1" in
    claude) printf '%s' "$CLAUDE_SKILLS_DIR" ;;
    codex) printf '%s' "$CODEX_SKILLS_DIR" ;;
    opencode) printf '%s' "$OPENCODE_SKILLS_DIR" ;;
    *) log "Unknown tool: $1"; exit 1 ;;
  esac
}

add_tool() {
  case " ${TOOLS[*]-} " in
    *" $1 "*) return 0 ;;
  esac
  TOOLS+=("$1")
}

select_tools() {
  local t
  TOOLS=()
  [ "$#" -gt 0 ] || set -- all
  for t in "$@"; do
    case "$t" in
      all)
        add_tool claude
        add_tool codex
        add_tool opencode
        ;;
      claude|codex|opencode)
        add_tool "$t"
        ;;
      *)
        log "Unknown tool: $t (choose all, claude, codex, opencode)"
        exit 1
        ;;
    esac
  done
}

managed_marker() {
  printf 'publish.sh skill:%s ' "$SKILL"
}

is_managed() {
  [ -f "$1" ] && grep -q "$(managed_marker)" "$1" 2>/dev/null
}

installed_version() {
  [ -f "$1" ] || { echo ""; return 0; }
  grep 'publish.sh' "$1" 2>/dev/null | grep -o 'version:[^ ]*' | head -1 | cut -d: -f2 || true
}

install_tool() {
  local tool="$1" root dest tmp lines
  root="$(tool_dir "$tool")"
  dest="$root/$SKILL/SKILL.md"
  tmp="$(mktemp)"
  {
    cat "$SKILL_FILE"
    printf '\n<!-- publish.sh skill:%s version:%s generated by publish.sh; edit SKILL.md and run ./publish.sh install -->\n' "$SKILL" "$VERSION"
  } > "$tmp"
  lines="$(wc -l < "$tmp" | tr -d ' ')"
  if [ "$DRY" = 1 ]; then
    log "  [dry] install $tool -> $dest ($lines lines)"
    rm -f "$tmp"
    return 0
  fi
  mkdir -p "$(dirname "$dest")"
  mv "$tmp" "$dest"
  log "  installed $tool -> $dest"
}

uninstall_tool() {
  local tool="$1" dest dir
  dest="$(tool_dir "$tool")/$SKILL/SKILL.md"
  dir="$(dirname "$dest")"
  if [ ! -e "$dest" ]; then
    log "  not installed $tool -> $dest"
    return 0
  fi
  if [ "$FORCE" != 1 ] && ! is_managed "$dest"; then
    log "  skip $tool -> $dest (not marked as managed; use --force to remove)"
    return 0
  fi
  if [ "$DRY" = 1 ]; then
    log "  [dry] uninstall $tool -> $dest"
    return 0
  fi
  rm -f "$dest"
  rmdir "$dir" 2>/dev/null || true
  log "  uninstalled $tool -> $dest"
}

status_tool() {
  local tool="$1" dest version
  dest="$(tool_dir "$tool")/$SKILL/SKILL.md"
  if [ ! -e "$dest" ]; then
    printf '  %-9s not installed\n' "$tool"
    return 0
  fi
  version="$(installed_version "$dest")"
  if is_managed "$dest"; then
    [ -n "$version" ] || version="?"
    if [ "$version" = "$VERSION" ]; then
      printf '  %-9s %s (current)\n' "$tool" "$version"
    else
      printf '  %-9s %s <- source %s\n' "$tool" "$version" "$VERSION"
    fi
  else
    printf '  %-9s installed, unmanaged\n' "$tool"
  fi
}

cmd_install() {
  local t
  require_skill
  select_tools "$@"
  log "install version: $VERSION"
  log "skill: $SKILL"
  [ "$DRY" = 1 ] && log "(dry-run)"
  for t in "${TOOLS[@]}"; do
    install_tool "$t"
  done
}

cmd_uninstall() {
  local t
  require_skill
  select_tools "$@"
  log "uninstall skill: $SKILL"
  [ "$DRY" = 1 ] && log "(dry-run)"
  for t in "${TOOLS[@]}"; do
    uninstall_tool "$t"
  done
}

cmd_status() {
  local t
  require_skill
  log "source version: $VERSION"
  log "skill:          $SKILL"
  for t in "${ALL_TOOLS[@]}"; do
    status_tool "$t"
  done
}

POS=""
for arg in "$@"; do
  case "$arg" in
    -n|--dry-run) DRY=1 ;;
    --force) FORCE=1 ;;
    -h|--help) usage; exit 0 ;;
    -*) log "Unknown option: $arg"; usage; exit 1 ;;
    *) POS="${POS:+$POS }$arg" ;;
  esac
done

# shellcheck disable=SC2086
set -- $POS
case "${1:-}" in
  install) shift; cmd_install "$@" ;;
  uninstall) shift; cmd_uninstall "$@" ;;
  status) shift; [ "$#" -eq 0 ] || { log "status does not accept tools"; exit 1; }; cmd_status ;;
  ""|help) usage ;;
  *) log "Unknown command: $1"; usage; exit 1 ;;
esac
