"""在临时源、命令搜索路径与目标目录中验证成组发布，不改写 HOME 或用户配置。"""

from contextlib import redirect_stdout, redirect_stderr
from dataclasses import replace
from io import StringIO
import os
from pathlib import Path
import plistlib
import stat
import subprocess
import tempfile
import unittest
from unittest.mock import patch

from scripts import publish


REPO = Path(__file__).resolve().parents[1]


def legacy_marker(version="old", skill="shanshi-coding"):
    return (f"<!-- publish.sh skill:{skill} version:{version} generated by publish.sh; "
            "edit SKILL.md and run ./publish.sh install -->\n").encode()


class PublishTest(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix="shanshi-publish-test-")
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.source = self.root / "source"
        (self.source / "common").mkdir(parents=True)
        self.body = b"---\nname: shanshi-coding\ndescription: fixture\n---\n\nSkill fixture\n"
        self.rules = "# 通用规则\n\n- 公共约定夹具。\n".encode()
        (self.source / "SKILL.md").write_bytes(self.body)
        (self.source / "common/AGENTS.md").write_bytes(self.rules)
        self.targets = publish.default_targets(self.root / "user", {})
        self.bin = self.root / "bin"
        self.bin.mkdir()
        self.apps = self.root / "Applications"

    def write(self, path, content):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        return path

    def install_command(self, tool):
        # 检测不得启动 agent；此命令如被执行会失败。
        command = self.write(self.bin / tool, b"#!/bin/sh\nexit 99\n")
        command.chmod(0o755)
        return command

    def detector(self, tool):
        return publish.detect_agent(tool, search_path=str(self.bin), app_roots=(self.apps,))

    def run_publish(self, *arguments, expected=0):
        output = StringIO()
        with redirect_stdout(output), redirect_stderr(output):
            result = publish.main(list(arguments), root=self.source, targets=self.targets, detector=self.detector)
        self.assertEqual(result, expected, output.getvalue())
        return output.getvalue()

    def assert_pair(self, tool):
        target = self.targets[tool]
        skill = target.skill.read_bytes()
        rules = target.active_rules().read_bytes()
        bundle = publish.Bundle(self.source)
        self.assertEqual(skill, self.body + b"\n" + legacy_marker(bundle.version))
        self.assertIn(self.rules.rstrip(b"\n"), rules)
        self.assertEqual(rules.count(b" begin -->"), 1)
        self.assertIn(f"version:{bundle.version} begin -->".encode(), rules)
        return rules, skill

    def test_auto_detection_install_update_and_idempotence(self):
        """场景：只装两个 CLI、另一个仅残留配置；核对选择范围、两文件同步更新及重复安装不叠加区块。"""
        for tool in ("codex", "opencode"):
            self.install_command(tool)
        unrelated = self.write(self.targets["claude"].rules, b"old config only\n")
        output = self.run_publish("install")
        self.assertIn("claude：未检测到；跳过", output)
        self.assertFalse(self.targets["claude"].skill.exists())
        old = {tool: self.assert_pair(tool) for tool in ("codex", "opencode")}
        self.run_publish("install", "all")
        self.assertEqual(old, {tool: self.assert_pair(tool) for tool in old})
        self.body += b"Changed coding preference\n"
        self.rules += "- 新的公共偏好。\n".encode()
        (self.source / "SKILL.md").write_bytes(self.body)
        (self.source / "common/AGENTS.md").write_bytes(self.rules)
        self.run_publish("install", "auto")
        for tool in old:
            new = self.assert_pair(tool)
            self.assertNotEqual(new[0], old[tool][0])
            self.assertNotEqual(new[1], old[tool][1])
        self.assertEqual(unrelated.read_bytes(), b"old config only\n")

    def test_desktop_detection_and_explicit_targets(self):
        """场景：没有 CLI 但有可运行的 Codex 桌面包；核对自动发现，未知安装位置可显式指定而不靠配置推断。"""
        self.assertIn("没有可处理的目标", self.run_publish("install"))
        self.assertFalse((self.root / "user").exists())
        app = self.apps / "Codex.app/Contents"
        executable = self.write(app / "MacOS/Codex", b"#!/bin/sh\nexit 99\n")
        executable.chmod(0o755)
        self.write(app / "Info.plist", plistlib.dumps({"CFBundleExecutable": "Codex"}))
        output = self.run_publish("install")
        self.assertIn("桌面应用", output)
        self.assert_pair("codex")
        self.assertFalse(self.targets["claude"].skill.exists())
        self.run_publish("install", "claude", "claude")
        self.assert_pair("claude")

    def test_common_update_and_uninstall_preserve_outside_bytes_and_permissions(self):
        """场景：公共文件含中文、CRLF、无末尾换行，安装后用户又加前缀；核对更新及卸载均保留区块外字节和权限。"""
        target = self.targets["claude"]
        original = "# 用户配置\r\n保留原有内容".encode()
        self.write(target.rules, original).chmod(0o640)
        self.run_publish("install", "claude")
        first = target.rules.read_bytes()
        prefix = b"# Added above the managed block\n\n"
        target.rules.write_bytes(prefix + first)
        self.rules += "- 更新公共规则。\n".encode()
        (self.source / "common/AGENTS.md").write_bytes(self.rules)
        self.run_publish("install", "claude")
        self.assertTrue(target.rules.read_bytes().startswith(prefix))
        self.assertTrue(target.rules.read_bytes().endswith(original))
        self.assertEqual(stat.S_IMODE(target.rules.stat().st_mode), 0o640)
        unrelated = self.write(target.skill.parent / "user-data.txt", b"keep\n")
        self.run_publish("uninstall")  # 即使 agent 已卸载，也按管理标记清理。
        self.assertEqual(target.rules.read_bytes(), prefix + original)
        self.assertFalse(target.skill.exists())
        self.assertEqual(unrelated.read_bytes(), b"keep\n")
        self.assertFalse(list(self.root.rglob(".shanshi-publish-*")))

    def test_legacy_upgrade_and_status_show_both_artifact_drifts(self):
        """场景：从仅有旧 skill 升级，再分别产生正文、版本和缺件偏差；状态必须逐文件报告，不能只看标签。"""
        self.write(self.targets["codex"].skill, b"legacy standalone skill\n" + legacy_marker())
        self.run_publish("install", *publish.TOOLS)
        self.assertEqual(self.run_publish("status").count("已同步（版本及内容已核对）"), 6)
        codex = self.targets["codex"]
        codex.rules.write_bytes(codex.rules.read_bytes().replace(self.rules, b"Changed rules\n"))
        claude = self.targets["claude"]
        claude.skill.write_bytes(self.body + b"\n" + legacy_marker("older"))
        self.targets["opencode"].skill.unlink()
        output = self.run_publish("status")
        for tool, state in (("codex", "内容不同"), ("claude", "版本不同"), ("opencode", "未安装")):
            with self.subTest(tool=tool):
                section = output.split(f"[{tool}]\n", 1)[1].split("\n[", 1)[0]
                self.assertIn(state, section)
        self.assertEqual(output.count("已同步（版本及内容已核对）"), 3)

    def test_predictable_pair_conflict_does_not_half_install_or_block_other_agents(self):
        """场景：一个工具已有非受管理 skill；整组预检阻止公共文件单独更新，其他工具继续，force 只替换 skill。"""
        target = self.targets["claude"]
        original_rules = b"personal instructions\n"
        original_skill = b"personal skill\n"
        self.write(target.rules, original_rules)
        self.write(target.skill, original_skill)
        output = self.run_publish("install", *publish.TOOLS, expected=1)
        self.assertIn("安装未完成", output)
        self.assertEqual(target.rules.read_bytes(), original_rules)
        self.assertEqual(target.skill.read_bytes(), original_skill)
        for tool in ("codex", "opencode"):
            self.assert_pair(tool)
        self.run_publish("--force", "install", "claude")
        self.assert_pair("claude")
        self.assertTrue(target.rules.read_bytes().endswith(original_rules))

    def test_footer_examples_and_invalid_ownership(self):
        """场景：正文包含尾注示例及各种伪管理标记；仅完整最终尾注授权替换，其他内容安装卸载都保护。"""
        self.body += legacy_marker("example") + b"body continues\n"
        (self.source / "SKILL.md").write_bytes(self.body)
        self.run_publish("install", "claude")
        self.assert_pair("claude")
        cases = {
            "正文提及": b"notes: publish.sh skill:shanshi-coding version:example\n",
            "非最终尾注": legacy_marker() + b"user text\n",
            "其他技能": legacy_marker(skill="other-skill"),
            "截断尾注": b"<!-- publish.sh skill:shanshi-coding version:old -->\n",
            "空版本": legacy_marker(version=""),
        }
        for scene, content in cases.items():
            with self.subTest(scene=scene):
                target = self.targets["claude"]
                target.skill.write_bytes(content)
                original_rules = target.rules.read_bytes()
                for action in ("install", "uninstall"):
                    self.run_publish(action, "claude", expected=1)
                    self.assertEqual(target.skill.read_bytes(), content)
                    self.assertEqual(target.rules.read_bytes(), original_rules)

    def test_damaged_common_markers_are_never_forced_over(self):
        """场景：公共区块重复、缺失结束标记或顺序颠倒；即使 force 也不猜范围，两份原文件保持不变。"""
        self.run_publish("install", "claude")
        target = self.targets["claude"]
        block = target.rules.read_bytes()
        skill = target.skill.read_bytes()
        cases = {"重复": block + block, "缺尾": block.split(b"end -->")[0],
                 "顺序": b"<!-- publish.sh common:shanshi-coding end -->\n\n" + block}
        for scene, content in cases.items():
            with self.subTest(scene=scene):
                target.rules.write_bytes(content)
                for action in ("install", "uninstall"):
                    output = self.run_publish("--force", action, "claude", expected=1)
                    self.assertIn("标记不完整或重复", output)
                    self.assertEqual(target.rules.read_bytes(), content)
                    self.assertEqual(target.skill.read_bytes(), skill)

    def test_write_failure_or_silent_corruption_restores_the_pair(self):
        """场景：第二份文件写入失败或被损坏，分别覆盖初装和升级；真实文件替换后核对成组恢复，其余工具继续发布。"""
        for existing in (False, True):
            for failure in ("raise", "corrupt"):
                with self.subTest(existing=existing, failure=failure):
                    target = self.targets["claude"]
                    for path in (target.rules, target.skill):
                        path.unlink(missing_ok=True)
                    before = {}
                    if existing:
                        self.write(target.rules, b"user instructions\n")
                        self.write(target.skill, b"old body\n" + legacy_marker())
                        before = {path: path.read_bytes() for path in (target.rules, target.skill)}
                    original_replace = os.replace
                    triggered = False

                    def faulty_replace(source, destination):
                        nonlocal triggered
                        if Path(destination) == target.skill and not triggered:
                            triggered = True
                            if failure == "raise":
                                raise OSError("injected write failure")
                            original_replace(source, destination)
                            target.skill.write_bytes(b"corrupted\n" + legacy_marker())
                            return
                        original_replace(source, destination)

                    with patch.object(publish.os, "replace", side_effect=faulty_replace):
                        output = self.run_publish("install", "claude", "opencode", expected=1)
                    self.assertTrue(triggered)
                    self.assertIn("已恢复", output)
                    for path in (target.rules, target.skill):
                        self.assertEqual(path.read_bytes() if path.exists() else None, before.get(path))
                    self.assert_pair("opencode")
                    self.assertFalse(list(self.root.rglob(".shanshi-publish-*")))

    def test_codex_override_migrates_only_the_managed_block(self):
        """场景：安装后新增 Codex override，随后卸载；区块迁往生效文件，普通文件和 override 的个人内容都保留。"""
        target = self.targets["codex"]
        self.write(target.rules, b"regular personal rules\n")
        self.run_publish("install", "codex")
        self.write(target.override, b"override personal rules\n")
        self.assertIn("需迁移旧公共区块", self.run_publish("status", "codex"))
        self.run_publish("install", "codex")
        self.assert_pair("codex")
        self.assertEqual(target.rules.read_bytes(), b"regular personal rules\n")
        self.assertTrue(target.override.read_bytes().endswith(b"override personal rules\n"))
        self.run_publish("uninstall", "codex")
        self.assertEqual(target.override.read_bytes(), b"override personal rules\n")
        self.assertEqual(target.rules.read_bytes(), b"regular personal rules\n")

    def test_dry_runs_do_not_write_and_uninstall_removes_only_managed_content(self):
        """场景：全新目标预览安装，真实安装后预览卸载；前后快照证明预览不写，卸载保留用户附属文件与源。"""
        output = self.run_publish("-n", "install", *publish.TOOLS)
        self.assertFalse((self.root / "user").exists())
        self.assertNotIn("均已核对", output)
        self.run_publish("install", *publish.TOOLS)
        installed = {p: p.read_bytes() for p in (self.root / "user").rglob("*") if p.is_file()}
        self.run_publish("uninstall", "all", "--dry-run")
        self.assertEqual(installed, {p: p.read_bytes() for p in installed})
        self.run_publish("uninstall", "all")
        self.assertTrue(all(not target.skill.exists() and not target.rules.exists() for target in self.targets.values()))
        self.assertEqual((self.source / "SKILL.md").read_bytes(), self.body)
        self.assertEqual((self.source / "common/AGENTS.md").read_bytes(), self.rules)

    def test_source_clone_protection_and_path_obstacles(self):
        """场景：skill 来自直接克隆、公共路径被文件夹占用或指向链接；安装不改源，强制卸载也不删源或越过路径障碍。"""
        self.targets["claude"] = replace(self.targets["claude"], skill=self.source / "SKILL.md")
        original_rules = b"personal rules\n"
        self.write(self.targets["claude"].rules, original_rules)
        output = self.run_publish("install", "claude")
        self.assertIn("源文件（内容一致）", output)
        self.assertEqual((self.source / "SKILL.md").read_bytes(), self.body)
        output = self.run_publish("--force", "uninstall", "claude")
        self.assertIn("保留源文件", output)
        self.assertEqual(self.targets["claude"].rules.read_bytes(), original_rules)
        self.assertEqual((self.source / "SKILL.md").read_bytes(), self.body)
        target = self.targets["codex"]
        target.rules.parent.mkdir(parents=True)
        target.rules.mkdir()
        self.run_publish("install", "codex", expected=1)
        self.assertFalse(target.skill.exists())
        target.rules.rmdir()
        linked = self.write(self.root / "dotfiles/rules.md", b"user rules\n")
        target.rules.symlink_to(linked)
        self.run_publish("--force", "install", "codex", expected=1)
        self.assertTrue(target.rules.is_symlink())
        self.assertEqual(linked.read_bytes(), b"user rules\n")
        self.assertFalse(target.skill.exists())

    def test_custom_config_locations_and_shell_entrypoint(self):
        """场景：工具使用自定义配置目录；核对路径映射、Codex 通用 skills 路径，以及实际 shell 入口可调用帮助。"""
        home = self.root / "custom-user"
        env = {"CODEX_HOME": str(self.root / "custom-codex"),
               "CLAUDE_CONFIG_DIR": str(self.root / "custom-claude"),
               "XDG_CONFIG_HOME": str(self.root / "custom-config")}
        self.targets = publish.default_targets(home, env)
        self.run_publish("install", *publish.TOOLS)
        for tool in publish.TOOLS:
            self.assert_pair(tool)
        self.assertEqual(self.targets["codex"].rules, Path(env["CODEX_HOME"]) / "AGENTS.md")
        self.assertEqual(self.targets["codex"].skill, home / ".agents/skills/shanshi-coding/SKILL.md")
        self.assertEqual(self.targets["claude"].rules, Path(env["CLAUDE_CONFIG_DIR"]) / "CLAUDE.md")
        self.assertEqual(self.targets["opencode"].rules, Path(env["XDG_CONFIG_HOME"]) / "opencode/AGENTS.md")
        env["OPENCODE_CONFIG_DIR"] = str(self.root / "custom-opencode")
        self.targets = publish.default_targets(home, env)
        self.run_publish("install", "opencode")
        self.assert_pair("opencode")
        self.assertEqual(self.targets["opencode"].rules, Path(env["OPENCODE_CONFIG_DIR"]) / "AGENTS.md")
        result = subprocess.run(["bash", str(REPO / "publish.sh"), "--help"], cwd=self.root,
                                capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("--dry-run", result.stdout)


if __name__ == "__main__":
    unittest.main()
