"""通过临时源目录和安装目录验证发布行为，不改写用户目录或 HOME。"""

from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest


REPO = Path(__file__).resolve().parents[1]
TOOLS = ("claude", "codex", "opencode")
SKILL = "shanshi-coding"


def marker(version="nogit", skill=SKILL):
    return (
        f"<!-- publish.sh skill:{skill} version:{version} generated by publish.sh; "
        "edit SKILL.md and run ./publish.sh install -->\n"
    )


class PublishTest(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix="shanshi-publish-test-")
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.source = self.root / "source" / SKILL
        self.source.mkdir(parents=True)
        self.script = self.source / "publish.sh"
        shutil.copyfile(REPO / "publish.sh", self.script)
        self.body = "---\nname: shanshi-coding\ndescription: 测试夹具\n---\n\nFixture body\n"
        (self.source / "SKILL.md").write_text(self.body)
        self.targets = {tool: self.root / tool for tool in TOOLS}

    def target(self, tool="claude"):
        return self.targets[tool] / SKILL / "SKILL.md"

    def write_target(self, content, tool="claude"):
        target = self.target(tool)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        return target

    def expected(self):
        return (self.body + "\n" + marker()).encode()

    def run_publish(self, *arguments, expected=0, before_main=""):
        # 只注入安装目录；实际调用脚本入口，保留真实解析、写入和校验逻辑。
        harness = '''source "$1"
CLAUDE_SKILLS_DIR="$2"
CODEX_SKILLS_DIR="$3"
OPENCODE_SKILLS_DIR="$4"
shift 4
'''
        result = subprocess.run(
            ["bash", "-c", harness + before_main + '\nmain "$@"', "publish-test",
             str(self.script), *(str(self.targets[tool]) for tool in TOOLS), *arguments],
            cwd=self.source, capture_output=True, text=True,
        )
        self.assertEqual(result.returncode, expected, result.stdout + result.stderr)
        return result.stdout

    def test_install_and_status_distinguish_content_version_and_missing_targets(self):
        """场景：三工具安装后各发生一种偏差；核对完整产物与各目标状态，标签相同不能掩盖正文变化。"""
        output = self.run_publish("install", "all")
        self.assertIn("all selected tools verified", output)
        for tool in TOOLS:
            self.assertEqual(self.target(tool).read_bytes(), self.expected())
        self.assertEqual(self.run_publish("status").count("(current, content verified)"), 3)

        self.write_target(self.body.replace("Fixture body", "Changed body") + "\n" + marker())
        self.write_target(self.body + "\n" + marker("older"), "codex")
        self.target("opencode").unlink()
        output = self.run_publish("status")
        for tool, state in [("claude", "content differs"), ("codex", "version differs"),
                            ("opencode", "not installed")]:
            with self.subTest(tool=tool):
                line = next(line for line in output.splitlines() if line.strip().startswith(tool + " "))
                self.assertIn(state, line)
        self.assertNotIn("(current", output)

    def test_body_examples_do_not_override_the_real_footer(self):
        """场景：正文含版本示例和完整旧尾注；安装及复查只认最终尾注，正文逐字保留。"""
        self.body += "publish.sh version:example\n" + marker("example") + "正文继续\n"
        (self.source / "SKILL.md").write_text(self.body)
        output = self.run_publish("install", "claude")
        self.assertIn("(current, content verified)", output)
        self.assertEqual(self.target().read_bytes(), self.expected())
        output = self.run_publish("status")
        self.assertIn("nogit (current, content verified)", output)

    def test_invalid_or_foreign_footer_does_not_authorize_overwrite_or_uninstall(self):
        """场景：不同格式的非受管理文件；安装报告跳过且失败，卸载也保留原始字节。"""
        cases = {
            "正文提及标记": "notes: publish.sh skill:shanshi-coding version:example\n",
            "标记不在末尾": marker() + "用户正文\n",
            "其他技能的尾注": "用户正文\n" + marker(skill="another-skill"),
            "缺少完整尾注": "<!-- publish.sh skill:shanshi-coding version:nogit -->\n",
            "空版本": marker(version=""),
        }
        for name, body in cases.items():
            with self.subTest(scene=name):
                target = self.write_target(body)
                original = target.read_bytes()
                output = self.run_publish("install", "claude", expected=1)
                self.assertIn("skip claude", output)
                self.assertIn("unmanaged", output)
                self.assertNotIn("all selected tools verified", output)
                self.assertEqual(target.read_bytes(), original)
                self.run_publish("uninstall", "claude")
                self.assertEqual(target.read_bytes(), original)

    def test_partial_install_reports_skipped_target_and_force_is_explicit(self):
        """场景：一个用户文件与两个空目标混合；其余目标照常安装，只有显式 force 才替换用户文件。"""
        original = self.write_target("用户已有内容\n").read_bytes()
        output = self.run_publish("install", "all", expected=1)
        self.assertEqual(self.target().read_bytes(), original)
        for tool in ("codex", "opencode"):
            self.assertEqual(self.target(tool).read_bytes(), self.expected())
        self.assertIn("installation incomplete", output)
        self.run_publish("--force", "install", "claude")
        self.assertEqual(self.target().read_bytes(), self.expected())

    def test_dry_run_and_uninstall_preserve_source_and_unrelated_files(self):
        """场景：预览安装、预览卸载、实际卸载；检查预览不写目标，实际卸载只移除受管理文件。"""
        output = self.run_publish("-n", "install", "all")
        self.assertNotIn("all selected tools verified", output)
        self.assertTrue(all(not self.target(tool).exists() for tool in TOOLS))
        self.run_publish("install", "all")
        unrelated = self.target().parent / "user-data.txt"
        unrelated.write_text("keep me\n")
        self.run_publish("-n", "uninstall", "all")
        for tool in TOOLS:
            self.assertEqual(self.target(tool).read_bytes(), self.expected())
        self.run_publish("uninstall", "all")
        self.assertTrue(all(not self.target(tool).exists() for tool in TOOLS))
        self.assertEqual(unrelated.read_text(), "keep me\n")
        self.assertEqual((self.source / "SKILL.md").read_text(), self.body)

    def test_same_file_install_is_current_without_adding_a_footer(self):
        """场景：仓库直接位于工具安装目录；验证同源跳过算成功，源文件不追加安装尾注。"""
        self.targets["claude"] = self.source.parent
        output = self.run_publish("install", "claude")
        self.assertIn("source file (current)", output)
        self.assertIn("all selected tools verified", output)
        self.assertEqual((self.source / "SKILL.md").read_text(), self.body)

    def test_post_install_check_detects_silent_content_corruption(self):
        """场景：写入返回成功但正文损坏、尾注保留；通过真实文件比对发现问题，继续校验其他目标。"""
        # 注入写入故障，校验机制仍执行脚本中的真实逻辑。
        fault = '''mv() {
  command mv "$@" || return 1
  if [[ "$2" == "$CLAUDE_SKILLS_DIR/"* ]]; then
    sed 's/Fixture body/Changed body/' "$2" > "$2.changed"
    command mv "$2.changed" "$2"
  fi
}
'''
        output = self.run_publish("install", "all", expected=1, before_main=fault)
        self.assertIn("content differs", output)
        self.assertIn("installation incomplete", output)
        self.assertNotEqual(self.target().read_bytes(), self.expected())
        for tool in ("codex", "opencode"):
            self.assertEqual(self.target(tool).read_bytes(), self.expected())

    def test_failed_write_preserves_obstacle_and_continues_other_targets(self):
        """场景：一个目标的父路径被普通文件占用；检查失败状态、障碍文件保留，其余目标仍完整安装。"""
        obstacle = self.targets["claude"]
        obstacle.write_text("existing file\n")
        output = self.run_publish("install", "all", expected=1)
        self.assertIn("failed claude", output)
        self.assertIn("installation incomplete", output)
        self.assertEqual(obstacle.read_text(), "existing file\n")
        for tool in ("codex", "opencode"):
            self.assertEqual(self.target(tool).read_bytes(), self.expected())


if __name__ == "__main__":
    unittest.main()
