"""成组发布公共规则与 skill；仅管理有明确标记的内容。"""

import argparse
from dataclasses import dataclass
import hashlib
import os
from pathlib import Path
import plistlib
import re
import shutil
import stat
import subprocess
import sys
import tempfile


TOOLS = ("codex", "claude", "opencode")
ROOT = Path(__file__).resolve().parents[1]


class PublishError(Exception):
    pass


def read_file(path):
    """不存在与空文件有不同的恢复语义，不读取目录或损坏链接。"""
    if path.is_symlink():
        raise PublishError(f"目标是符号链接，请先确认其管理方式：{path}")
    try:
        return path.read_bytes()
    except FileNotFoundError:
        return None


def same_file(left, right):
    return left.exists() and right.exists() and left.samefile(right)


@dataclass(frozen=True)
class Target:
    name: str
    rules: Path
    skill: Path
    override: Path = None

    def rule_paths(self):
        return [self.rules] + ([self.override] if self.override else [])

    def active_rules(self):
        # Codex 的非空 override 会遮蔽同级 AGENTS.md。
        if self.override and read_file(self.override):
            return self.override
        return self.rules


def default_targets(home, env):
    codex = Path(env.get("CODEX_HOME") or home / ".codex").expanduser()
    claude = Path(env.get("CLAUDE_CONFIG_DIR") or home / ".claude").expanduser()
    config = Path(env.get("XDG_CONFIG_HOME") or home / ".config").expanduser()
    opencode = Path(env.get("OPENCODE_CONFIG_DIR") or config / "opencode").expanduser()
    relative = Path("shanshi-coding/SKILL.md")
    return {
        "codex": Target("codex", codex / "AGENTS.md", home / ".agents/skills" / relative,
                        codex / "AGENTS.override.md"),
        "claude": Target("claude", claude / "CLAUDE.md", claude / "skills" / relative),
        "opencode": Target("opencode", opencode / "AGENTS.md", opencode / "skills" / relative),
    }


def detect_agent(tool, search_path=None, app_roots=()):
    command = shutil.which(tool, path=search_path)
    if command:
        return f"命令：{command}"
    # Claude 桌面聊天应用不作为 Claude Code 已安装的证据。
    app_names = {"codex": ("Codex.app",), "opencode": ("OpenCode.app", "opencode.app")}
    for root in app_roots:
        for name in app_names.get(tool, ()):
            app = root / name
            try:
                with (app / "Contents/Info.plist").open("rb") as stream:
                    executable = plistlib.load(stream).get("CFBundleExecutable", "")
                binary = app / "Contents/MacOS" / executable
                if executable and binary.is_file() and os.access(binary, os.X_OK):
                    return f"桌面应用：{app}"
            except (OSError, ValueError, plistlib.InvalidFileException):
                continue
    return None


class Bundle:
    def __init__(self, root, version=None):
        self.skill_path = root / "SKILL.md"
        self.rules_path = root / "common/AGENTS.md"
        self.skill = self.skill_path.read_bytes()
        self.rules = self.rules_path.read_bytes()
        frontmatter = self.skill.decode("utf-8").split("---", 2)
        if len(frontmatter) != 3 or frontmatter[0]:
            raise PublishError("SKILL.md 缺少 frontmatter")
        if not re.search(r"^name: shanshi-coding\s*$", frontmatter[1], re.M):
            raise PublishError("SKILL.md 的 name 必须为 shanshi-coding")
        if not self.rules.decode("utf-8").strip():
            raise PublishError("公共规则不能为空")
        self.prefix = b"<!-- publish.sh common:shanshi-coding "
        if self.prefix in self.rules:
            raise PublishError("公共规则源文件不可包含发布管理标记")
        if version is None:
            try:
                revision = subprocess.run(
                    ["git", "-C", str(root), "describe", "--tags", "--always", "--dirty"],
                    capture_output=True, text=True, check=True,
                ).stdout.strip()
            except (OSError, subprocess.CalledProcessError):
                revision = "nogit"
            digest = hashlib.sha256(self.rules + b"\0" + self.skill).hexdigest()[:12]
            version = f"{revision}.{digest}"
        self.version = version

    @staticmethod
    def footer(version):
        return (f"<!-- publish.sh skill:shanshi-coding version:{version} generated by publish.sh; "
                "edit SKILL.md and run ./publish.sh install -->\n").encode()

    def render_skill(self, version=None):
        return self.skill + b"\n" + self.footer(version or self.version)

    def skill_version(self, content):
        if not content:
            return None
        line = content.splitlines()[-1]
        match = re.fullmatch(rb"<!-- publish.sh skill:shanshi-coding version:(\S+) "
                             rb"generated by publish.sh; edit SKILL.md and run ./publish.sh install -->", line)
        return match[1].decode("utf-8") if match else None

    def render_rules(self, version=None):
        begin = self.prefix + f"version:{version or self.version} begin -->\n".encode()
        return begin + self.rules.rstrip(b"\n") + b"\n" + self.prefix + b"end -->\n\n"

    def rules_block(self, content):
        """返回唯一完整管理区块；拒绝重复或损坏标记，避免误删用户内容。"""
        content = content or b""
        markers = list(re.finditer(rb"^" + re.escape(self.prefix) + rb".*$", content, re.M))
        if not markers:
            return None
        block = re.search(
            rb"^" + re.escape(self.prefix) + rb"version:(\S+) begin -->\n.*?^"
            + re.escape(self.prefix) + rb"end -->\n\n", content, re.M | re.S,
        )
        if (len(markers) != 2 or not block or block.start() != markers[0].start()
                or not (block.start() < markers[1].start() < block.end())):
            raise PublishError("公共规则管理标记不完整或重复；保留原文件，请先整理标记")
        return block


@dataclass
class Change:
    path: Path
    before: bytes
    after: bytes


def plan_changes(bundle, target, action, force):
    changes = []
    active = target.active_rules()
    for path in target.rule_paths():
        if same_file(path, bundle.rules_path):
            continue
        content = read_file(path)
        block = bundle.rules_block(content)
        if action == "install" and path == active:
            rendered = bundle.render_rules()
            updated = (content[:block.start()] + rendered + content[block.end():]
                       if block else rendered + (content or b""))
        elif block:
            # override 切换或卸载时，只清除本脚本拥有的区块。
            updated = (content[:block.start()] + content[block.end():]) or None
        else:
            continue
        if content != updated:
            changes.append(Change(path, content, updated))

    if same_file(target.skill, bundle.skill_path):
        return changes
    content = read_file(target.skill)
    if content is not None and not bundle.skill_version(content) and not force:
        raise PublishError(f"SKILL.md 非本脚本管理；确认替换或移除时显式使用 --force：{target.skill}")
    updated = bundle.render_skill() if action == "install" else None
    if content != updated:
        changes.append(Change(target.skill, content, updated))
    return changes


def apply_changes(changes):
    """先暂存一组文件及原始内容；写入或核对失败时恢复该工具的整组改动。"""
    staged, backups, written, created_dirs = {}, {}, [], []

    def stage(path, content, mode):
        descriptor, name = tempfile.mkstemp(prefix=".shanshi-publish-", dir=path.parent)
        temporary = Path(name)
        try:
            with os.fdopen(descriptor, "wb") as stream:
                stream.write(content)
                os.fchmod(stream.fileno(), mode)
            return temporary
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise

    try:
        for change in changes:
            if read_file(change.path) != change.before:
                raise PublishError(f"准备期间文件已变化，停止写入：{change.path}")
            missing = []
            parent = change.path.parent
            while not parent.exists():
                missing.append(parent)
                parent = parent.parent
            for directory in reversed(missing):
                directory.mkdir()
                created_dirs.append(directory)
            mode = stat.S_IMODE(change.path.stat().st_mode) if change.before is not None else 0o600
            if change.before is not None:
                backups[change.path] = stage(change.path, change.before, mode)
            if change.after is not None:
                staged[change.path] = stage(change.path, change.after, mode)
        for change in changes:
            if read_file(change.path) != change.before:
                raise PublishError(f"写入前文件已变化，停止写入：{change.path}")
            if change.after is None:
                change.path.unlink()
            else:
                os.replace(staged[change.path], change.path)
            written.append(change)
        for change in changes:
            if read_file(change.path) != change.after:
                raise PublishError(f"写入后内容核对失败：{change.path}")
    except BaseException as error:
        failures = []
        for change in reversed(written):
            try:
                if change.before is None:
                    change.path.unlink(missing_ok=True)
                else:
                    os.replace(backups[change.path], change.path)
            except OSError as restore_error:
                failures.append(f"{change.path}：{restore_error}；原内容备份：{backups.get(change.path)}")
        if failures:
            # 保留恢复失败的备份，避免同时失去目标文件与恢复依据。
            backups = {}
            raise PublishError(f"{error}；恢复未完成：{'；'.join(failures)}") from error
        if not isinstance(error, Exception):
            raise  # 用户中止时恢复当前工具，然后结束，不继续安装其他工具。
        raise PublishError(f"{error}；本工具已写入的改动已恢复") from error
    finally:
        for temporary in [*staged.values(), *backups.values()]:
            temporary.unlink(missing_ok=True)
        for directory in reversed(created_dirs):
            try:
                directory.rmdir()
            except OSError:
                pass


def status_target(bundle, target):
    current = True
    active = target.active_rules()
    for label, path, source in [("公共规则", active, bundle.rules_path),
                                 ("coding skill", target.skill, bundle.skill_path)]:
        if same_file(path, source):
            state, ok = "源文件（内容一致）", True
        else:
            content = read_file(path)
            if label == "公共规则":
                block = bundle.rules_block(content)
                version = block[1].decode("utf-8") if block else None
                actual = block[0] if block else content
                expected = bundle.render_rules(version)
            else:
                version = bundle.skill_version(content)
                actual, expected = content, bundle.render_skill(version)
            ok = False
            if content is None:
                state = "未安装"
            elif version is None:
                state = "无管理标记"
            elif actual != expected:
                state = f"内容不同（已装 {version}）"
            elif version != bundle.version:
                state = f"版本不同（已装 {version}，内容一致）"
            else:
                state, ok = "已同步（版本及内容已核对）", True
        print(f"  {label}：{path}\n    {state}")
        current = current and ok
    for path in target.rule_paths():
        if path != active and bundle.rules_block(read_file(path)):
            print(f"  需迁移旧公共区块：{path}（当前被 override 遮蔽）")
            current = False
    return current


def has_managed_content(bundle, target):
    if not same_file(target.skill, bundle.skill_path) and bundle.skill_version(read_file(target.skill)):
        return True
    return any(not same_file(path, bundle.rules_path) and bundle.prefix in (read_file(path) or b"")
               for path in target.rule_paths())


def main(argv=None, *, root=ROOT, targets=None, detector=None):
    parser = argparse.ArgumentParser(description="成组安装公共协作约定与 coding skill，默认只选择本机检测到的 agent。")
    parser.add_argument("-n", "--dry-run", action="store_true", help="预览，不改动文件")
    parser.add_argument("--force", action="store_true", help="允许替换或移除非受管理的 SKILL.md，不覆盖公共文件")
    parser.add_argument("action", choices=("install", "uninstall", "status"))
    parser.add_argument("tools", nargs="*", help="auto/all 或 codex、claude、opencode；具体工具名可用于未检测到的安装")
    args = parser.parse_intermixed_args(argv)
    if any(tool not in (*TOOLS, "auto", "all") for tool in args.tools):
        parser.error("工具名只能是 auto、all、codex、claude 或 opencode")
    if any(tool in ("all", "auto") for tool in args.tools) and len(args.tools) > 1:
        parser.error("all/auto 不与具体工具名混用")
    try:
        bundle = Bundle(root)
        targets = targets if targets is not None else default_targets(Path.home(), os.environ)
        app_roots = (Path("/Applications"), Path.home() / "Applications") if sys.platform == "darwin" else ()
        detector = detector or (lambda tool: detect_agent(tool, app_roots=app_roots))
        detected = {tool: detector(tool) for tool in TOOLS}
        explicit = bool(args.tools and args.tools[0] not in ("auto", "all"))
        if explicit:
            selected = list(dict.fromkeys(args.tools))
        elif args.action == "status":
            selected = list(TOOLS)
        elif args.action == "uninstall":
            selected = []
            for tool in TOOLS:
                try:
                    if has_managed_content(bundle, targets[tool]):
                        selected.append(tool)
                except (OSError, PublishError):
                    selected.append(tool)  # 在工具级报告问题，继续处理其他目标。
        else:
            selected = [tool for tool in TOOLS if detected[tool]]
        print(f"源版本：{bundle.version}")
        if args.dry_run:
            print("预览模式：不写入文件")
        for tool in TOOLS:
            print(f"{tool}：{detected[tool] or '未检测到'}" + ("" if tool in selected else "；跳过"))
        if not selected:
            print("没有可处理的目标；可显式指定 codex、claude 或 opencode。")
            return 0
        failed = False
        for tool in selected:
            target = targets[tool]
            print(f"[{tool}]")
            try:
                if args.action == "status":
                    status_target(bundle, target)
                    continue
                changes = plan_changes(bundle, target, args.action, args.force)
                for change in changes:
                    print(f"  {'移除' if change.after is None else '更新'}：{change.path}")
                if args.dry_run:
                    if not changes:
                        print("  无需变更")
                    continue
                apply_changes(changes)
                if args.action == "install":
                    if not status_target(bundle, target):
                        raise PublishError("公共规则与 skill 未同时通过核对")
                else:
                    if has_managed_content(bundle, target):
                        raise PublishError("仍有受管理内容未卸载")
                    for path, source in [(target.skill, bundle.skill_path),
                                         (target.active_rules(), bundle.rules_path)]:
                        if same_file(path, source):
                            print(f"  保留源文件，请自行管理源仓库：{path}")
                    try:
                        target.skill.parent.rmdir()
                    except OSError:
                        pass
                    print("  已移除受管理内容，保留其他配置")
            except (OSError, UnicodeError, PublishError) as error:
                print(f"  失败：{error}")
                failed = True
        if args.action == "install" and not args.dry_run:
            print("安装未完成，请检查上面的失败项" if failed else "所选工具的公共规则与 skill 均已核对")
        # status 是诊断命令；偏差通过正文报告，不作为失败退出。
        return 1 if failed and args.action != "status" else 0
    except (OSError, UnicodeError, PublishError) as error:
        print(f"失败：{error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
